# Generated by Django 4.2.3 on 2023-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_savedwork_user_remove_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_plan_id',
            field=models.CharField(choices=[('price_1NmG4RCOAyay7VTLqfqUxOud', 'Free'), ('price_1NmG4RCOAyay7VTLPcRACV7i', 'Premium'), ('free_plan_id', 'Free'), ('premium_plan_id', 'Premium')], max_length=50),
        ),
    ]
