# Generated by Django 4.2.3 on 2023-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_stripe_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_plan_id',
            field=models.CharField(choices=[('price_1NmG4RCOAyay7VTLqfqUxOud', 'Free'), ('price_1NmG4RCOAyay7VTLPcRACV7i', 'Premium')], max_length=50),
        ),
    ]
